export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  mongodbUri: process.env.MONGODB_URI ?? "",
  isProduction: process.env.NODE_ENV === "production",
  discordGatewayEnabled: process.env.DISCORD_GATEWAY_ENABLED === "true" || process.env.NODE_ENV !== "production",
  jobWorkerEnabled: process.env.JOB_WORKER_ENABLED === "true" || process.env.NODE_ENV !== "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  discordBotToken: process.env.DISCORD_BOT_TOKEN ?? "",
  discordApplicationId: process.env.DISCORD_APPLICATION_ID ?? "",
  discordGuildId: process.env.DISCORD_GUILD_ID ?? "",
  ownerDiscordUserId: process.env.OWNER_DISCORD_USER_ID ?? "",
  googleDriveApiKey: process.env.GDRIVE_API_KEY ?? "",
  googleDriveClientId: process.env.GDRIVE_CLIENT_ID ?? "",
  googleDriveClientSecret: process.env.GDRIVE_CLIENT_SECRET ?? "",
  googleDriveRefreshToken: process.env.GDRIVE_REFRESH_TOKEN ?? "",
  suwayomiBaseUrl: process.env.SUWAYOMI_BASE_URL ?? "",
  suwayomiApiToken: process.env.SUWAYOMI_API_TOKEN ?? "",
  integrationMonitorToken: process.env.INTEGRATION_MONITOR_TOKEN ?? "",
  adminEmail: process.env.ADMIN_EMAIL ?? "admin@manga-drive.local",
  adminPassword: process.env.ADMIN_PASSWORD ?? "ChangeMeNow!2026",
};
