import { Client, Events, GatewayIntentBits, MessageFlags, REST, Routes, SlashCommandBuilder, type APIMessageTopLevelComponent } from "discord.js";
import { ENV } from "../_core/env";
import { addJobAttempt, cancelChapterJob, getChapterJob, listActiveDiscordRoleIds, saveIntegrationHealth, setDiscordProgressMessage } from "../db";
import { queueAuthorizedChapter } from "./jobs";
import { UrlPolicyError } from "./urlPolicy";
let client: Client | null = null; let started = false;
export type JobNotice = { jobId?: string; status: "pending" | "downloading" | "uploading" | "completed" | "failed" | "cancelled" | "info"; title: string; description: string; pageCount?: number; uploadedPages?: number; driveUrl?: string | null };
const divider = "━━━━━━━━━━━━━━━━━━━━"; const statusCopy = { pending: ["في الطابور", "المرحلة 1 من 4 — التحقق من الرابط"], downloading: ["جارٍ جلب الصفحات", "المرحلة 2 من 4 — جلب الفصل من Suwayomi"], uploading: ["جارٍ الرفع إلى Drive", "المرحلة 3 من 4 — حفظ الصفحات بترتيبها"], completed: ["اكتملت العملية", "المرحلة 4 من 4 — جاهز للتسليم"], failed: ["تعذرت العملية", "توقفت المعالجة"], cancelled: ["أُلغي الطلب", "أُوقفت المعالجة"], info: ["Manga Drive", "معلومة"] } as const;
function chapterCommand(name: "فصل" | "chapter") { return new SlashCommandBuilder().setName(name).setDescription(name === "فصل" ? "حفظ فصل مصرح به في Google Drive" : "Save an authorized chapter to Google Drive").addStringOption(option => option.setName(name === "فصل" ? "الرابط" : "url").setDescription("رابط الفصل الكامل").setRequired(true)); }
const commandPayload = [chapterCommand("فصل"), chapterCommand("chapter"), new SlashCommandBuilder().setName("مساعدة").setDescription("طريقة استخدام Manga Drive"), new SlashCommandBuilder().setName("help").setDescription("How to use Manga Drive")].map(command => command.toJSON());
export function getRegisteredDiscordCommands() { return commandPayload; }
function isOwner(userId: string) { return Boolean(ENV.ownerDiscordUserId) && userId === ENV.ownerDiscordUserId; }
async function hasRequestAccess(interaction: any) { if (!interaction.inGuild() || !interaction.member || !interaction.channelId) return false; if (isOwner(interaction.user.id)) return true; const allowed = await listActiveDiscordRoleIds(); const roles = Array.isArray(interaction.member.roles) ? interaction.member.roles : interaction.member.roles.cache.map((role: { id: string }) => role.id); return allowed.some(role => roles.includes(role)); }
function component(value: Record<string, unknown>): APIMessageTopLevelComponent { return value as unknown as APIMessageTopLevelComponent; }
function progressText(notice: JobNotice) { const stage = statusCopy[notice.status][1]; if (notice.status === "uploading" && notice.pageCount) return `**${stage}**\n> تم رفع ${notice.uploadedPages ?? 0} من ${notice.pageCount} صفحة.`; if (notice.status === "downloading" && notice.pageCount) return `**${stage}**\n> عُثر على ${notice.pageCount} صفحة. يجري تجهيزها للرفع.`; return `**${stage}**\n> ${notice.description}`; }
function buttons(notice: JobNotice, final = false): APIMessageTopLevelComponent | null { const list: Record<string, unknown>[] = []; if (final && notice.driveUrl) list.push({ type: 2, style: 5, label: "فتح مجلد Google Drive", url: notice.driveUrl }); if (!final && notice.jobId && ["pending", "downloading", "uploading"].includes(notice.status)) list.push({ type: 2, style: 2, label: "إلغاء الطلب", custom_id: `job:cancel:${notice.jobId}` }); return list.length ? component({ type: 1, components: list }) : null; }
export function buildJobComponents(notice: JobNotice, options?: { requesterId?: string; final?: boolean }): APIMessageTopLevelComponent[] { const body: APIMessageTopLevelComponent[] = [component({ type: 10, content: `${options?.requesterId ? `<@${options.requesterId}>\n` : ""}## ${statusCopy[notice.status][0]}` }), component({ type: 14, divider: true, spacing: 1 }), component({ type: 10, content: progressText(notice) }), component({ type: 14, divider: true, spacing: 1 }), component({ type: 10, content: `${notice.pageCount ? `**الصفحات:** ${notice.pageCount}` : "**المصدر:** Suwayomi"}\n${divider}\nManga Drive · مصادر مصرح بها فقط` })]; const row = buttons(notice, Boolean(options?.final)); if (row) body.push(row); return [component({ type: 17, accent_color: notice.status === "completed" ? 0x57f287 : notice.status === "failed" ? 0xed4245 : 0x000000, components: body })]; }
function payload(notice: JobNotice, options?: { requesterId?: string; final?: boolean }) { return { flags: MessageFlags.IsComponentsV2 as MessageFlags.IsComponentsV2, allowedMentions: options?.requesterId ? { users: [options.requesterId] } : undefined, components: buildJobComponents(notice, options) }; }
function fromJob(job: { id: string; status: string; totalPages: number; uploadedPages: number; googleDriveUrl: string | null; failureMessage: string | null }): JobNotice { const status = (["pending", "downloading", "uploading", "completed", "failed", "cancelled"].includes(job.status) ? job.status : "info") as JobNotice["status"]; const description = status === "completed" ? "اكتمل رفع الصفحات بالترتيب إلى Google Drive." : status === "failed" ? job.failureMessage ?? "تعذر إكمال المعالجة." : status === "cancelled" ? "أُلغي الطلب قبل اكتمال رفع الصفحات." : "الطلب قيد المعالجة."; return { jobId: job.id, status, title: "طلب فصل", description, pageCount: job.totalPages || undefined, uploadedPages: job.uploadedPages, driveUrl: job.googleDriveUrl }; }
export async function refreshDiscordCommands() { if (!ENV.discordBotToken || !ENV.discordApplicationId || !ENV.discordGuildId) return; await new REST({ version: "10" }).setToken(ENV.discordBotToken).put(Routes.applicationGuildCommands(ENV.discordApplicationId, ENV.discordGuildId), { body: commandPayload }); }
export function isDiscordBotReady() { return Boolean(client?.isReady()); }
async function replyHelp(interaction: any) { await interaction.deferReply(); await interaction.editReply({ content: ["## Manga Drive", divider, "**/فصل** أو **/chapter** يقبل رابط فصل كاملًا من مصدر مصرح به.", "تظهر بطاقة التقدم في القناة ثم تُرسل رسالة مستقلة بمنشن الطالب ورابط Google Drive.", "تُدار الحالات والسجل من لوحة الإدارة."] .join("\n") }); }
async function replyChapter(interaction: any) { await interaction.deferReply(); try { if (!(await hasRequestAccess(interaction))) { await interaction.editReply({ content: "لا تملك دورًا معتمدًا لاستخدام أوامر الفصول." }); return; } const name = interaction.commandName === "chapter" ? "url" : "الرابط"; const { job, created } = await queueAuthorizedChapter({ chapterUrl: interaction.options.getString(name, true), requester: { discordId: interaction.user.id, displayName: interaction.user.username, channelId: interaction.channelId } }); if (!created) { await interaction.editReply({ content: `هذا الرابط مسجل بالفعل ضمن طلب ${statusCopy[fromJob(job).status][0]}. تابع لوحة الإدارة.` }); return; } const progress = await interaction.editReply(payload({ jobId: job.id, status: "pending", title: "طلب فصل", description: "تلقى Manga Drive الرابط ويجري فحص المصدر المصرح به." })); await setDiscordProgressMessage(job.id, progress.id); void import("./jobWorker").then(({ processPendingChapterJobs }) => processPendingChapterJobs()); } catch (error) { const message = error instanceof UrlPolicyError ? error.message : "تعذر قبول الرابط. تحقق من المصدر وإعداداته ثم أعد المحاولة."; await interaction.editReply({ content: `تعذر بدء الطلب. ${message}` }); } }
async function handleButton(interaction: any) { if (!interaction.customId.startsWith("job:cancel:")) return; await interaction.deferUpdate(); const job = await getChapterJob(interaction.customId.split(":")[2]); if (!job || (!isOwner(interaction.user.id) && job.requestedByDiscordId !== interaction.user.id)) return; try { const cancelled = await cancelChapterJob(job.id); await addJobAttempt(job.id, "cancelled", `ألغى العضو ${interaction.user.username} المهمة من Discord.`); await updateJobProgressMessage(cancelled.requestedInChannelId, cancelled.discordProgressMessageId, fromJob(cancelled)); } catch (error) { console.warn("[Discord] Could not cancel job", error); } }
export async function startDiscordBot() { if (started || !ENV.discordBotToken || !ENV.discordApplicationId || !ENV.discordGuildId) return; started = true; client = new Client({ intents: [GatewayIntentBits.Guilds] }); client.once(Events.ClientReady, async ready => { console.info(`[Discord] Connected as ${ready.user.tag}`); try { await refreshDiscordCommands(); console.info(`[Discord] Guild commands refreshed (${commandPayload.length})`); await saveIntegrationHealth("discord", "healthy", `البوت متصل وحُدّثت ${commandPayload.length} أوامر.`); } catch (error) { console.error("[Discord] Command registration failed", error); } }); client.on(Events.InteractionCreate, async interaction => { try { if (interaction.isButton()) return void handleButton(interaction); if (!interaction.isChatInputCommand()) return; if (["مساعدة", "help"].includes(interaction.commandName)) await replyHelp(interaction); else if (["فصل", "chapter"].includes(interaction.commandName)) await replyChapter(interaction); } catch (error) { console.error("[Discord] Interaction handler failed", error); if (interaction.isRepliable()) { if (interaction.deferred || interaction.replied) await interaction.editReply({ content: "تعذر تنفيذ الأمر الآن.", components: [] }).catch(() => undefined); else await interaction.reply({ content: "تعذر تنفيذ الأمر الآن." }).catch(() => undefined); } } }); client.on(Events.Error, error => { console.error("[Discord] Client error", error); void saveIntegrationHealth("discord", "offline", "تعرض اتصال Discord لخطأ."); }); await client.login(ENV.discordBotToken); }
async function channel(channelId: string | null) { if (!client || !channelId) return null; const found = await client.channels.fetch(channelId); return found?.isTextBased() && "send" in found ? found : null; }
export async function updateJobProgressMessage(channelId: string | null, messageId: string | null, notice: JobNotice) { if (!client || !channelId || !messageId) return; const found = await client.channels.fetch(channelId); if (!found?.isTextBased() || !("messages" in found)) return; try { const message = await found.messages.fetch(messageId); await message.edit(payload(notice)); } catch (error) { console.warn(`[Discord] Could not update progress message ${messageId}`, error); } }
export async function sendJobUpdate(channelId: string | null, requesterId: string, notice: JobNotice) { const job = notice.jobId ? await getChapterJob(notice.jobId) : undefined; await updateJobProgressMessage(channelId, job?.discordProgressMessageId ?? null, notice); if (!["completed", "failed", "cancelled"].includes(notice.status)) return; const found = await channel(channelId); if (found) await found.send(payload(notice, { requesterId, final: true })); }
export async function sendOwnerAlert(message: string) { if (!client || !ENV.ownerDiscordUserId) return; const owner = await client.users.fetch(ENV.ownerDiscordUserId); await owner.send({ content: `## تنبيه المنصة\n${divider}\n${message}` }); }
